version: '3.7'

networks:
  pman:

services:
  db:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pman
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - pman

  backend:
    build: .
    command: python /repo/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/repo
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - pman
